### PR TITLE
 added CAIP-25 to remove the round-trip required for wallet_getCapabilities

### PR DESCRIPTION
**Pull request by KannuSingh**
on session approval, wallet capabilities data as defined for wallet_getCapabilities in EIP5792 is added to sessionProperties,
this gives another way for dapps to check wallet's capabilities without requesting via wallet_getCapabilities method.

### CODE REVIEW

**Comment by lukaisailovic** [comment]
Are we supposed to also implement logic dapp side to check for this?

**Comment by KannuSingh** [comment]
Not sure how to showcase this on dapp side.
Some suggestion 
I can add a card on react-dapp-v2 showing capabilities or update the account cards with methods call such that if certain EIP5792 capabilities is not present for any account on connected chain it will don't have EIP5792 methods displayed.

Example on react-dapp-v2 for EOA account card we can remove wallet_sendCalls, wallet_getCallsStatus methods as we are not supporting batch calls for EOA.

**Comment by lukaisailovic** [comment]
> Not sure how to showcase this on dapp side. Some suggestion I can add a card on react-dapp-v2 showing capabilities or update the account cards with methods call such that if certain EIP5792 capabilities is not present for any account on connected chain it will don't have EIP5792 methods displayed.
> 
> Example on react-dapp-v2 for EOA account card we can remove wallet_sendCalls, wallet_getCallsStatus methods as we are not supporting batch calls for EOA.

@KannuSingh Well the point was to remove additional network trip that dapps have to do with `wallet_getCapabilities` and offer that information in CAIP-25 response instead.

We can update `react-dapp-v2` to show `sessionProperties`, and disable buttons that trigger batch call for example if its not available. 

I like your idea of showing received `sessionProperties` dapp side too 👌

**Comment by KannuSingh** [comment]
okay, I will add this in the react-dapp-v2.

**Review by arein — COMMENTED** [review]
lgtm. can you add a test?

**Comment by KannuSingh** [comment]
This change filtered the actions for account, but if we want to only want to disable buttons for those action I can also add those changes instead of removing the actions.

**Comment by arein** [comment]
I meant an automatic eg unit test to cover this logic and help prevent regressions would also be great

**Review by arein — APPROVED** [review]

**Comment by lukaisailovic** [comment]
> okay, I will add this in the react-dapp-v2.
> 
> One another thing I would to check is currently sessionProperties is having type `Record<string, string>`, will it be change to `Record<string, Object>` in future?

If it changes we'll update. For not its `Record<string, string>`

**Pull request merged**
