### PR TITLE
Chore/wallet 155 fix

### PR DESCRIPTION
**Pull request by JonathanConn**
Fixed the dep issue
Bug with swc and nextjs version

Wallet seems unstable, only worked with older v2 + ethers
https://react-dapp-v2-with-ethers.vercel.app/

Is this worth fixing?

### CODE REVIEW

**Review by 0xAsimetriq — COMMENTED** [review]
Unless we know of someone using this example, it might be worth deleting it

**Comment by bkrem** [comment]
> Unless we know of someone using this example, it might be worth deleting it

Appreciate you applying the boyscout rule here @JonathanConn but I also had this on my list for deletion 😅

**Review by 0xAsimetriq — APPROVED** [review]
Great fix 😄

**Review by ganchoradkov — APPROVED** [review]
💯

**Review by bkrem — APPROVED** [review]

**Comment by bkrem** [comment]
I've also cleaned up the Vercel project ✅ 

Thank you for handling here @JonathanConn 🙏

**Pull request merged**
